/* eslint-disable prettier/prettier */
export const SEARCH_MOVIES = 'SEARCH_MOVIES';
export const SEARCH_MOVIES_SUCCESS = 'SEARCH_MOVIES_SUCCESS';
export const SEARCH_MOVIES_FAIL = 'SEARCH_MOVIES_FAIL';

export const GET_DETAILS = 'GET_DETAILS';
export const GET_DETAILS_SUCCESS = 'GET_DETAILS_SUCCESS';
export const GET_DETAILS_FAIL = 'GET_DETAILS_FAIL';

export const SAVE_DETAILS_IN_WATCHLIST = 'SAVE_DETAILS_IN_WATCHLIST';
export const SAVE_DETAILS_IN_WATCHLIST_SUCCESS = 'SAVE_DETAILS_IN_WATCHLIST_SUCCESS';
export const SAVE_DETAILS_IN_WATCHLIST_FAIL = 'SAVE_DETAILS_IN_WATCHLIST_FAIL';

export const DELETE_DETAILS_FROM_WATCHLIST = 'DELETE_DETAILS_FROM_WATCHLIST';
export const DELETE_DETAILS_FROM_WATCHLIST_SUCCESS = 'DELETE_DETAILS_FROM_WATCHLIST_SUCCESS';
export const DELETE_DETAILS_FROM_WATCHLIST_FAIL = 'DELETE_DETAILS_FROM_WATCHLIST_FAIL';



